@startuml
enum com.senla.hotel.constant.ServiceType {
+  NONE
+  REPAIR
+  MAINTENANCE
+  CLEANING
}
class com.senla.menu.MenuMain {
- {static} Navigator NAVIGATOR
- {static} PropertiesService PROPERTIES_SERVICE
- {static} Builder BUILDER
- {static} MenuController MENU_CONTROLLER
- {static} String MENU_DESCRIPTION_FILENAME
+ {static} void main(String[])
}
interface com.senla.hotel.service.IGuestService {
~ void saveAll(List<Guest>)
}
class com.senla.menu.action.impl.MenuAction6 {
+ void execute()
}
class com.senla.menu.action.impl.MenuAction12 {
+ void execute()
}
class com.senla.menu.action.impl.MenuAction1 {
+ void execute()
}
class com.senla.hotel.dao.impl.BookingDAOImpl {
- {static} BookingDAOImpl INSTANCE
- {static} Set<Long> idHolder
- Map<Long,Booking> bookings
+ {static} BookingDAOImpl getInstance()
+ List<Booking> getAll()
+ void saveAll(List<Booking>)
+ Booking getById(long)
+ void save(Booking)
+ Booking update(Booking)
}
class com.senla.menu.action.impl.MenuAction7 {
+ void execute()
}
enum com.senla.hotel.constant.GuestServicesSection {
+  PRICE
+  DATE
}
class com.senla.hotel.service.impl.RoomServicesServiceImpl {
- {static} RoomServicesServiceImpl INSTANCE
- IEntityDAO<RoomService> roomServiceDAO
+ {static} RoomServicesServiceImpl getInstance()
+ void saveAll(List<RoomService>)
+ List<RoomService> getAllOrdered(RoomServiceSection,Ordering)
+ void updateAllAndSaveIfNotExist(ArrayList<RoomService>)
+ List<RoomService> getAll()
}
class com.senla.menu.entity.Menu {
- String title
- Map<Integer,IAction> items
}
interface com.senla.hotel.dao.IEntityDAO {
~ List<T> getAll()
~ T getById(long)
~ void save(T)
~ void saveAll(List<T>)
~ T update(T)
~ long generateId(Set<Long>)
}
class com.senla.hotel.entity.RoomService {
- long id
- ServiceType serviceType
- double price
+ String toString()
}
class com.senla.hotel.entity.Guest {
- long id
- String firstName
- String lastName
+ String toString()
}
interface com.senla.menu.action.IAction {
~ void execute()
}
class com.senla.hotel.service.impl.GuestServicesServiceImpl {
- {static} GuestServicesServiceImpl INSTANCE
- IEntityDAO<GuestServices> guestServicesDAO
- IEntityDAO<RoomService> roomServiceDAO
+ {static} GuestServicesServiceImpl getInstance()
+ void saveAll(List<GuestServicesEntityDTO>)
+ List<GuestServicesDTO> getByGuestIdSorted(long,GuestServicesSection,Ordering)
+ void updateAllAndSaveIfNotExist(ArrayList<GuestServices>)
+ List<GuestServicesEntityDTO> getAll()
+ GuestServicesEntityDTO getById(long)
+ GuestServices guestServiceConvertFromDTOtoEntity(GuestServicesEntityDTO)
- GuestServicesEntityDTO guestServiceConvertFromEntityToDTO(GuestServices)
- Map<Date,Long> jsonStringToMapConvert(String)
- String mapToJsonStringConvert(Map<Date,Long>)
}
class com.senla.menu.controller.MenuController {
- {static} MenuController INSTANCE
- Scanner scanner
- Menu menu
- Navigator navigator
- String menuDescriptionFileName
- Builder builder
+ {static} MenuController getInstance()
+ void setBuilder(Builder)
+ void setMenu(Menu)
+ void setNavigator(Navigator)
+ void setMenuDescriptionFileName(String)
+ MenuController showMenu()
+ void menuRolling()
}
enum com.senla.hotel.constant.Ordering {
+  ASC
+  DESC
}
class com.senla.menu.navigator.Navigator {
- {static} Navigator INSTANCE
- PropertiesService propertiesService
+ {static} Navigator getInstance()
+ void setPropertiesService(PropertiesService)
+ void navigate(Menu,String)
}
interface com.senla.hotelio.service.IImportService {
~ ArrayList<T> getEntitiesFromCsv(String)
}
class com.senla.hotelio.service.entityimport.ImportServiceOld {
- {static} ImportService INSTANCE
+ {static} String PATH
+ {static} String FILE_EXTENSION
+ {static} String PACKAGE_PATH
+ {static} String DELIMITER
+ {static} ImportService getInstance()
+ ArrayList<T> getEntitiesFromCsv(String)
- Object createInstance(String,String)
}
class com.senla.hotel.dao.impl.RoomServiceDAOImpl {
- {static} RoomServiceDAOImpl INSTANCE
- {static} Set<Long> idHolder
- Map<Long,RoomService> roomServices
+ {static} RoomServiceDAOImpl getInstance()
+ List<RoomService> getAll()
+ void saveAll(List<RoomService>)
+ RoomService update(RoomService)
+ RoomService getById(long)
+ void save(RoomService)
}
class com.senla.hotel.dao.impl.GuestServicesDAOImpl {
- {static} GuestServicesDAOImpl INSTANCE
- {static} Set<Long> idHolder
- Map<Long,GuestServices> guestServices
+ {static} GuestServicesDAOImpl getInstance()
+ List<GuestServices> getAll()
+ void saveAll(List<GuestServices>)
+ GuestServices update(GuestServices)
+ GuestServices getById(long)
+ void save(GuestServices)
}
class com.senla.hotel.entity.Room {
- long id
- int capacity
- double price
- boolean isAvailable
- long roomServiceId
- int starsRating
+ String toString()
}
class com.senla.menu.entity.MenuItem {
- Integer position
- IAction action
}
abstract class com.senla.menu.action.MenuAction {
# Scanner scanner
# BookingServiceImpl bookingService
# GuestServicesServiceImpl guestServicesService
# RoomServiceImpl roomService
# RoomServicesServiceImpl roomServicesService
# GuestServiceImpl guestService
# ImportService importService
# ExportService exportService
# Ordering getOrdering()
}
class com.senla.hotelio.service.entityimport.ExportService {
- {static} ExportService INSTANCE
+ {static} String PATH
+ {static} String EXTENSION
+ {static} String REGEX
+ {static} ExportService getInstance()
+ void storeEntityToCsv(String)
- String getFieldsFromEntityInCsvFormat(Object)
}
class com.senla.hotel.dao.impl.GuestDAOImpl {
- {static} GuestDAOImpl INSTANCE
- {static} Set<Long> idHolder
- Map<Long,Guest> guests
+ {static} GuestDAOImpl getInstance()
+ List<Guest> getAll()
+ void saveAll(List<Guest>)
+ Guest update(Guest)
+ Guest getById(long)
+ void save(Guest)
}
class com.senla.menu.action.impl.MenuAction13 {
+ void execute()
}
class com.senla.hotel.service.impl.GuestServiceImpl {
- {static} GuestServiceImpl INSTANCE
- GuestDAOImpl guestDAO
+ {static} GuestServiceImpl getInstance()
+ void saveAll(List<Guest>)
+ void updateAllAndSaveIfNotExist(ArrayList<Guest>)
+ List<Guest> getAll()
}
class com.senla.menu.action.impl.MenuAction16 {
+ void execute()
}
interface com.senla.hotel.service.IBookingService {
~ void saveAll(List<Booking>)
~ List<GuestBookingDTO> findAllOrderedAlphabetically()
~ List<Booking> findAllOrderedByCheckOutDate()
~ List<Booking> findLastGuestOfRoomAndDates(int,long)
~ double getTotalPaymentByGuest(long)
~ List<Room> findAvailableRoomsByDate(Date)
~ long findCountOfAllGuests()
~ Booking getByGuestId(long)
}
class com.senla.hotel.dao.impl.RoomDAOImpl {
- {static} RoomDAOImpl INSTANCE
- {static} Set<Long> idHolder
- Map<Long,Room> rooms
+ {static} RoomDAOImpl getInstance()
+ Room update(Room)
+ Room getById(long)
+ void save(Room)
+ List<Room> getAll()
+ void saveAll(List<Room>)
}
class com.senla.hotel.dto.GuestServicesDTO {
- {static} Set<Long> idHolder
- long id
- Date date
- RoomService roomService
- void generateId()
+ String toString()
}
class com.senla.menu.action.impl.MenuAction10 {
+ void execute()
}
class com.senla.menu.action.impl.MenuAction9 {
+ void execute()
}
interface com.senla.hotel.service.IRoomServicesService {
~ void saveAll(List<RoomService>)
~ List<RoomService> getAllOrdered(RoomServiceSection,Ordering)
}
enum com.senla.hotel.constant.RoomSection {
+  ID
+  CAPACITY
+  PRICE
+  AVAILABILITY
+  SERVICE
+  RATING
}
class com.senla.menu.action.impl.MenuAction3 {
+ void execute()
}
class com.senla.hotel.dto.GuestServicesEntityDTO {
- long id
- long guestId
- Map<Date,Long> servicesOrdered
}
class com.senla.hotel.Hotel {
- {static} Hotel INSTANCE
+ {static} void init()
}
class com.senla.menu.action.impl.MenuAction15 {
+ void execute()
}
interface com.senla.hotel.service.IGuestServicesService {
~ void saveAll(List<GuestServicesEntityDTO>)
~ List<GuestServicesDTO> getByGuestIdSorted(long,GuestServicesSection,Ordering)
}
class com.senla.menu.action.impl.MenuAction4 {
+ void execute()
}
class com.senla.hotel.dto.GuestBookingDTO {
- {static} Set<Long> idHolder
- long id
- Guest guest
- Booking booking
- void generateId()
}
interface com.senla.hotelio.service.IExportService {
~ void storeEntityToCsv(String)
}
class com.senla.menu.action.impl.MenuAction11 {
+ void execute()
}
class com.senla.hotel.service.impl.RoomServiceImpl {
- {static} RoomServiceImpl INSTANCE
- IEntityDAO<Room> roomDAO
+ {static} RoomServiceImpl getInstance()
+ void saveAll(List<Room>)
+ void doCheckIn(long)
+ void doCheckOut(long)
+ Room changeRoomService(long,long)
+ Room changeRoomPrice(long,double)
+ Room getRoom(long)
+ void addRoom(Room)
+ List<Room> findAllOrderedByPrice()
+ List<Room> findAllOrderedByCapacity()
+ List<Room> findAllOrderedByStars()
+ List<Room> findAvailableOrderedByPrice()
+ List<Room> findAvailableOrderedByCapacity()
+ List<Room> findAvailableOrderedByStars()
+ int findNumberOfAvailableRooms()
+ double getRoomPrice(long)
+ List<Room> getAllOrdered(RoomSection,Ordering)
+ void updateAllAndSaveIfNotExist(ArrayList<Room>)
+ List<Room> getAll()
}
class com.senla.menu.builder.Builder {
- {static} Builder INSTANCE
- Map<Integer,IAction> items
- String title
+ {static} Builder getInstance()
+ Map<Integer,IAction> getItems()
+ Builder setTitle(String)
+ Builder addItem(MenuItem)
+ Menu build()
}
interface com.senla.hotel.service.IRoomService {
~ void saveAll(List<Room>)
~ void doCheckIn(long)
~ void doCheckOut(long)
~ Room changeRoomService(long,long)
~ Room changeRoomPrice(long,double)
~ Room getRoom(long)
~ void addRoom(Room)
~ List<Room> findAllOrderedByPrice()
~ List<Room> findAllOrderedByCapacity()
~ List<Room> findAllOrderedByStars()
~ List<Room> findAvailableOrderedByPrice()
~ List<Room> findAvailableOrderedByCapacity()
~ List<Room> findAvailableOrderedByStars()
~ int findNumberOfAvailableRooms()
~ double getRoomPrice(long)
~ List<Room> getAllOrdered(RoomSection,Ordering)
}
class com.senla.menu.action.impl.MenuAction14 {
+ void execute()
}
class com.senla.menu.action.impl.MenuAction8 {
+ void execute()
}
class com.senla.menu.service.PropertiesService {
- {static} PropertiesService INSTANCE
- Map<Integer,String> menuMap
+ {static} PropertiesService getInstance()
+ Map<Integer,String> readPropertiesFileAsMap(String,String)
}
class com.senla.menu.action.impl.MenuAction5 {
+ void execute()
}
class com.senla.hotel.entity.GuestServices {
- long id
- long guestId
- String servicesOrdered
}
class com.senla.hotel.entity.Booking {
- long id
- long guestId
- long guestServicesId
- long bookedRoomId
- Date checkInDate
- Date checkOutDate
+ String toString()
}
class com.senla.hotel.service.impl.BookingServiceImpl {
- {static} BookingServiceImpl INSTANCE
- IEntityDAO<Booking> bookingDAO
- IEntityDAO<Room> roomDAO
- IEntityDAO<Guest> guestDAO
+ {static} BookingServiceImpl getInstance()
+ void saveAll(List<Booking>)
+ List<GuestBookingDTO> findAllOrderedAlphabetically()
+ List<Booking> findAllOrderedByCheckOutDate()
+ List<Booking> findLastGuestOfRoomAndDates(int,long)
+ double getTotalPaymentByGuest(long)
+ List<Room> findAvailableRoomsByDate(Date)
+ long findCountOfAllGuests()
+ Booking getByGuestId(long)
+ void updateAllAndSaveIfNotExist(ArrayList<Booking>)
+ List<Booking> getAll()
}
class com.senla.hotelio.Runner {
+ {static} void main(String[])
}
enum com.senla.hotel.constant.RoomServiceSection {
+  ROOM_SERVICE
+  PRICE
}
class com.senla.menu.action.impl.MenuAction2 {
+ void execute()
}


com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction6
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction6
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction12
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction12
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction1
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction1
com.senla.hotel.dao.IEntityDAO <|.. com.senla.hotel.dao.impl.BookingDAOImpl
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction7
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction7
com.senla.hotel.service.IRoomServicesService <|.. com.senla.hotel.service.impl.RoomServicesServiceImpl
com.senla.hotel.service.IGuestServicesService <|.. com.senla.hotel.service.impl.GuestServicesServiceImpl
com.senla.hotelio.service.IImportService <|.. com.senla.hotelio.service.entityimport.ImportServiceOld
com.senla.hotel.dao.IEntityDAO <|.. com.senla.hotel.dao.impl.RoomServiceDAOImpl
com.senla.hotel.dao.IEntityDAO <|.. com.senla.hotel.dao.impl.GuestServicesDAOImpl
com.senla.hotelio.service.IExportService <|.. com.senla.hotelio.service.entityimport.ExportService
com.senla.hotel.dao.IEntityDAO <|.. com.senla.hotel.dao.impl.GuestDAOImpl
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction13
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction13
com.senla.hotel.service.IGuestService <|.. com.senla.hotel.service.impl.GuestServiceImpl
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction16
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction16
com.senla.hotel.dao.IEntityDAO <|.. com.senla.hotel.dao.impl.RoomDAOImpl
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction10
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction10
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction9
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction9
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction3
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction3
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction15
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction15
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction4
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction4
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction11
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction11
com.senla.hotel.service.IRoomService <|.. com.senla.hotel.service.impl.RoomServiceImpl
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction14
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction14
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction8
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction8
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction5
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction5
com.senla.hotel.service.IBookingService <|.. com.senla.hotel.service.impl.BookingServiceImpl
com.senla.menu.action.IAction <|.. com.senla.menu.action.impl.MenuAction2
com.senla.menu.action.MenuAction <|-- com.senla.menu.action.impl.MenuAction2
@enduml